// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package cardsim

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type AggregatedStats struct {
	_tab flatbuffers.Table
}

func GetRootAsAggregatedStats(buf []byte, offset flatbuffers.UOffsetT) *AggregatedStats {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &AggregatedStats{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *AggregatedStats) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *AggregatedStats) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *AggregatedStats) TotalGames() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *AggregatedStats) MutateTotalGames(n uint32) bool {
	return rcv._tab.MutateUint32Slot(4, n)
}

func (rcv *AggregatedStats) Player0Wins() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *AggregatedStats) MutatePlayer0Wins(n uint32) bool {
	return rcv._tab.MutateUint32Slot(6, n)
}

func (rcv *AggregatedStats) Player1Wins() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *AggregatedStats) MutatePlayer1Wins(n uint32) bool {
	return rcv._tab.MutateUint32Slot(8, n)
}

func (rcv *AggregatedStats) Draws() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *AggregatedStats) MutateDraws(n uint32) bool {
	return rcv._tab.MutateUint32Slot(10, n)
}

func (rcv *AggregatedStats) AvgTurns() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *AggregatedStats) MutateAvgTurns(n float32) bool {
	return rcv._tab.MutateFloat32Slot(12, n)
}

func (rcv *AggregatedStats) MedianTurns() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *AggregatedStats) MutateMedianTurns(n uint32) bool {
	return rcv._tab.MutateUint32Slot(14, n)
}

func (rcv *AggregatedStats) AvgDurationNs() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *AggregatedStats) MutateAvgDurationNs(n uint64) bool {
	return rcv._tab.MutateUint64Slot(16, n)
}

func (rcv *AggregatedStats) Errors() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *AggregatedStats) MutateErrors(n uint32) bool {
	return rcv._tab.MutateUint32Slot(18, n)
}

func AggregatedStatsStart(builder *flatbuffers.Builder) {
	builder.StartObject(8)
}
func AggregatedStatsAddTotalGames(builder *flatbuffers.Builder, totalGames uint32) {
	builder.PrependUint32Slot(0, totalGames, 0)
}
func AggregatedStatsAddPlayer0Wins(builder *flatbuffers.Builder, player0Wins uint32) {
	builder.PrependUint32Slot(1, player0Wins, 0)
}
func AggregatedStatsAddPlayer1Wins(builder *flatbuffers.Builder, player1Wins uint32) {
	builder.PrependUint32Slot(2, player1Wins, 0)
}
func AggregatedStatsAddDraws(builder *flatbuffers.Builder, draws uint32) {
	builder.PrependUint32Slot(3, draws, 0)
}
func AggregatedStatsAddAvgTurns(builder *flatbuffers.Builder, avgTurns float32) {
	builder.PrependFloat32Slot(4, avgTurns, 0.0)
}
func AggregatedStatsAddMedianTurns(builder *flatbuffers.Builder, medianTurns uint32) {
	builder.PrependUint32Slot(5, medianTurns, 0)
}
func AggregatedStatsAddAvgDurationNs(builder *flatbuffers.Builder, avgDurationNs uint64) {
	builder.PrependUint64Slot(6, avgDurationNs, 0)
}
func AggregatedStatsAddErrors(builder *flatbuffers.Builder, errors uint32) {
	builder.PrependUint32Slot(7, errors, 0)
}
func AggregatedStatsEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
